from pydantic import BaseModel, Field
from typing import Optional, List


class ReportRequest(BaseModel):
    """
    Request payload for generating the standardized report.
    """

    focus_area: Optional[str] = Field(
        None,
        description="Optional context to refine the report (e.g., 'Analyze H3N2 variant impact').",
    )


class ChatRequest(BaseModel):
    """
    Request payload for ad-hoc follow-up questions.
    """

    query: str = Field(..., description="User question for the agent.")


class AgentResponse(BaseModel):
    """
    Standardized response format.
    """

    response: str = Field(..., description="The Markdown text generated by the agent.")
    plots: List[str] = Field(
        default_factory=list,
        description="List of generated plot filenames referenced in the text.",
    )
    execution_time: float
