import logging
import mlflow

from api.src.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


def _create_offline_markdown(original_text: str, plot_filenames: list[str]) -> str:
    """
    Internal Helper: Converts API URLs to relative local paths for archived reports.

    The API generates reports with online links (e.g., `/api/v1/plots/chart.png`)
    so the frontend can render them. However, for long-term storage (MLflow/S3),
    these links must be converted to relative paths (e.g., `plots/chart.png`)
    so the markdown remains valid when downloaded as a zip artifact.

    Args:
        original_text (str): The raw markdown generated by the Agent.
        plot_filenames (list[str]): List of valid plot files actually generated.

    Returns:
        str: The modified markdown text with relative image paths.
    """
    offline_text = original_text

    for filename in plot_filenames:
        api_path = f"/api/v1/plots/{filename}"
        local_path = f"plots/{filename}"

        offline_text = offline_text.replace(api_path, local_path)

    return offline_text


def upload_run_artifacts(response_text: str, generated_plots: list[str]):
    """
    Packages and uploads run artifacts (report text and charts) to the MLflow Tracking Server.

    This function ensures governance and reproducibility by permanently storing
    the output of each agent execution.

    **Fail-Safe Mechanism:**
    This function is designed to be non-blocking. It catches all internal exceptions
    to ensure that a storage failure (e.g., S3 down) does not crash the main API response
    returned to the user.

    **Steps:**

    1.  **Check Context:** Verifies if there is an active MLflow run.
    2.  **Upload Plots:** Iterates through `generated_plots`, validates their existence
        on disk, and uploads them to the `plots/` artifact folder.
    3.  **Process Report:** Converts the Markdown to an "offline" version using
        `_create_offline_markdown`.
    4.  **Upload Report:** Logs the modified text as `report.md`.

    Args:
        response_text (str): The full markdown report text.
        generated_plots (list[str]): List of filenames for plots generated in this run.
    """
    if not settings.MLFLOW_ENABLE:
        return

    try:
        run = mlflow.last_active_run()

        if not run:
            logger.warning("No active MLflow run found. Skipping artifact upload.")
            return

        run_id = run.info.run_id
        logger.info(f"Packaging artifacts for Run ID: {run_id}")

        for filename in generated_plots:
            file_path = settings.PLOTS_DIR / filename

            if file_path.exists():
                mlflow.log_artifact(local_path=str(file_path), artifact_path="plots")
                logger.debug(f"   -> Uploaded: {filename}")
            else:
                logger.warning(f"   -> File missing on disk: {filename}")

        report_offline = _create_offline_markdown(response_text, generated_plots)
        mlflow.log_text(report_offline, "report.md")

        logger.info("Artifact Package (Report + Plots) uploaded successfully.")

    except Exception as e:
        logger.error(f"Governance upload failed: {e}", exc_info=True)
